// Strict human-rights focused sources.
// Even from dedicated rights orgs, we still run every story through the keyword filter
// — orgs publish corporate news, fundraising, market reports, etc. We want only stories
// that defend, document, or amplify human-rights situations.

// trusted=true → rights-org/UN feed; positive keyword can be in TITLE *or* SUMMARY.
// trusted=false → general news; positive keyword MUST be in TITLE (stricter, drops political headlines).
module.exports = [
  // ===== English: rights/humanitarian orgs (trusted) =====
  { source: 'Human Rights Watch',    url: 'https://www.hrw.org/rss/news',                                 lang: 'en', topic: 'rights', trusted: true },
  { source: 'Amnesty International', url: 'https://www.amnesty.org/en/latest/news/feed/',                 lang: 'en', topic: 'rights', trusted: true },
  { source: 'ReliefWeb',             url: 'https://reliefweb.int/updates/rss.xml',                        lang: 'en', topic: 'humanitarian', trusted: true },
  { source: 'UN News',               url: 'https://news.un.org/feed/subscribe/en/news/all/rss.xml',       lang: 'en', topic: 'rights', trusted: true },
  { source: 'IFRC',                  url: 'https://www.ifrc.org/rss.xml',                                 lang: 'en', topic: 'humanitarian', trusted: true },
  { source: 'ICRC Blog',             url: 'https://blogs.icrc.org/feed/',                                 lang: 'en', topic: 'humanitarian', trusted: true },
  { source: 'Save the Children',     url: 'https://www.savethechildren.net/news?title=&date_filter%5Bvalue%5D%5Bdate%5D=&page=0&rss=1', lang: 'en', topic: 'children', trusted: true },
  { source: 'Global Voices',         url: 'https://globalvoices.org/feed/',                               lang: 'en', topic: 'rights', trusted: true },
  { source: 'IPS News',              url: 'https://www.ipsnews.net/feed/',                                lang: 'en', topic: 'rights', trusted: true },
  // ===== English: general news (strict — keyword must be in title) =====
  { source: 'Al Jazeera',            url: 'https://www.aljazeera.com/xml/rss/all.xml',                    lang: 'en', topic: 'rights', trusted: false },
  { source: 'BBC World',             url: 'https://feeds.bbci.co.uk/news/world/rss.xml',                  lang: 'en', topic: 'rights', trusted: false },

  // ===== Turkish =====
  { source: 'Global Voices TR',      url: 'https://tr.globalvoices.org/feed/',                            lang: 'tr', topic: 'rights', trusted: true },
  { source: 'BBC Türkçe',            url: 'https://feeds.bbci.co.uk/turkce/rss.xml',                      lang: 'tr', topic: 'rights', trusted: false },
  { source: 'DW Türkçe',             url: 'https://rss.dw.com/rdf/rss-tur-all',                           lang: 'tr', topic: 'rights', trusted: false },
  { source: 'AA Dünya',              url: 'https://www.aa.com.tr/tr/rss/default?cat=dunya',               lang: 'tr', topic: 'rights', trusted: false },

  // ===== French =====
  { source: 'ONU Info',              url: 'https://news.un.org/feed/subscribe/fr/news/all/rss.xml',       lang: 'fr', topic: 'rights', trusted: true },
  { source: 'Amnesty France',        url: 'https://www.amnesty.org/fr/latest/news/feed/',                 lang: 'fr', topic: 'rights', trusted: true },
  { source: 'Global Voices FR',      url: 'https://fr.globalvoices.org/feed/',                            lang: 'fr', topic: 'rights', trusted: true },
  { source: 'Le Monde Afrique',      url: 'https://www.lemonde.fr/afrique/rss_full.xml',                  lang: 'fr', topic: 'rights', trusted: false },
  { source: 'RFI Monde',             url: 'https://www.rfi.fr/fr/monde/rss',                              lang: 'fr', topic: 'rights', trusted: false },
  { source: 'France 24',             url: 'https://www.france24.com/fr/rss',                              lang: 'fr', topic: 'rights', trusted: false },
];

// ===== Positive keywords — every story MUST match at least one. =====
// Strictly rights-oriented vocabulary; we avoid generic "aid"/"famine"/"rescue" alone.
module.exports.KEYWORDS = {
  en: [
    'human rights', 'civil rights', 'civil liberties', 'civilian', 'civilians',
    'refugee', 'refugees', 'asylum', 'displaced', 'displacement', 'idp',
    'torture', 'tortured', 'detained', 'detention', 'arrested', 'imprisoned',
    'prisoner of conscience', 'political prisoner', 'enforced disappearance',
    'extrajudicial', 'death penalty', 'execution', 'execute',
    'war crime', 'crimes against humanity', 'genocide', 'ethnic cleansing',
    'massacre', 'atrocity', 'atrocities',
    'press freedom', 'journalist killed', 'journalist detained', 'journalist jailed', 'reporter killed',
    'free expression', 'freedom of expression', 'freedom of assembly', 'freedom of speech',
    'women rights', "women's rights", 'gender violence', 'sexual violence', 'femicide',
    'children rights', "children's rights", 'child labor', 'child marriage', 'child soldier',
    'minority rights', 'indigenous rights', 'lgbt rights', 'lgbtq', 'discrimination',
    'human trafficking', 'trafficked', 'slavery', 'forced labor', 'forced labour',
    'religious freedom', 'persecuted', 'persecution', 'crackdown',
    'unlawful', 'arbitrary', 'rights violation', 'rights abuse', 'rights defender',
    'civic space', 'civil society', 'activist arrested', 'activist killed',
    'protest crackdown', 'protesters', 'demonstrators',
    'humanitarian crisis', 'humanitarian disaster', 'aid worker killed', 'aid worker',
    'ceasefire', 'truce', 'peace deal', 'reconciliation',
    'survivor', 'survivors', 'witness', 'testimony',
  ],
  tr: [
    'insan hakları', 'sivil haklar', 'sivil özgürlük', 'sivil',
    'mülteci', 'sığınmacı', 'göçmen', 'yerinden edilen',
    'işkence', 'gözaltı', 'tutuklu', 'tutuklandı', 'cezaevi',
    'siyasi tutuklu', 'vicdan tutuklusu', 'kayıp', 'zorla kaybedilme',
    'yargısız infaz', 'idam', 'idama',
    'savaş suç', 'insanlığa karşı suç', 'soykırım', 'etnik temizlik',
    'katliam', 'mezalim',
    'basın özgürlüğü', 'gazeteci öldürüldü', 'gazeteci tutuklandı', 'gazeteci gözaltı',
    'ifade özgürlüğü', 'toplanma özgürlüğü', 'düşünce özgürlüğü',
    'kadın hakları', 'kadın cinayeti', 'cinsel şiddet', 'cinsel saldırı',
    'çocuk hakları', 'çocuk işçi', 'çocuk gelin', 'çocuk asker',
    'azınlık hakları', 'yerli halk', 'lgbti', 'ayrımcılık',
    'insan kaçakçılığı', 'köle', 'zorla çalıştırma',
    'inanç özgürlüğü', 'baskı', 'zulüm',
    'hak ihlali', 'hak savunucusu', 'sivil toplum',
    'protesto', 'eylemci', 'gösterici',
    'insani kriz', 'yardım çalışanı', 'ateşkes', 'barış',
    'tanık', 'kurtulan',
  ],
  fr: [
    'droits humains', "droits de l'homme", 'libertés civiles', 'civil', 'civils',
    'réfugié', 'réfugiés', 'asile', 'déplacé', 'déplacement',
    'torture', 'détenu', 'détention', 'arrêté', 'emprisonné',
    'prisonnier de conscience', 'prisonnier politique', 'disparition forcée',
    'exécution extrajudiciaire', 'peine de mort', 'exécution',
    'crime de guerre', "crime contre l'humanité", 'génocide', 'nettoyage ethnique',
    'massacre', 'atrocité', 'atrocités',
    'liberté de la presse', 'journaliste tué', 'journaliste détenu', 'journaliste emprisonné',
    'liberté d\'expression', 'liberté de réunion',
    'droits des femmes', 'violence faite aux femmes', 'violence sexuelle', 'féminicide',
    "droits de l'enfant", 'travail des enfants', 'mariage forcé', 'enfant soldat',
    'droits des minorités', 'peuples autochtones', 'lgbt', 'discrimination',
    'traite humaine', 'esclavage', 'travail forcé',
    'liberté religieuse', 'persécuté', 'persécution', 'répression',
    'violation des droits', "violation des droits humains", 'défenseur des droits',
    'société civile', 'manifestation', 'manifestant',
    'crise humanitaire', 'travailleur humanitaire', 'cessez-le-feu', 'paix',
    'témoin', 'survivant',
  ],
};

// ===== Strong-rights keywords — required IN TITLE for general-news feeds. =====
// Subset of positive keywords that signal a story is clearly about rights/violations.
module.exports.STRONG = {
  en: [
    'human rights', 'rights violation', 'rights abuse', 'rights defender',
    'civilian', 'civilians', 'civilian killed', 'civilian deaths', 'civilian casualties',
    'refugee', 'refugees', 'asylum seeker', 'displaced', 'displacement', 'idp',
    'torture', 'tortured', 'detained', 'detention', 'jailed', 'imprisoned',
    'prisoner of conscience', 'political prisoner', 'enforced disappearance', 'disappeared',
    'death penalty', 'execution', 'extrajudicial',
    'war crime', 'crimes against humanity', 'genocide', 'ethnic cleansing',
    'massacre', 'atrocity', 'atrocities',
    'press freedom', 'journalist killed', 'journalist detained', 'journalist jailed', 'reporter killed',
    'freedom of expression', 'freedom of assembly', 'freedom of speech',
    "women's rights", 'gender violence', 'sexual violence', 'femicide', 'sexual assault',
    "children's rights", 'child labour', 'child labor', 'child marriage', 'child soldier',
    'minority rights', 'indigenous rights', 'lgbt rights', 'lgbtq',
    'human trafficking', 'trafficked', 'slavery', 'forced labour', 'forced labor',
    'religious freedom', 'persecuted', 'persecution', 'crackdown',
    'aid worker killed', 'aid worker detained',
    'survivor', 'survivors',
    'discrimination', 'racism', 'xenophobia',
    'activist arrested', 'activist killed', 'protest crackdown',
    'starvation', 'famine',
    'civilian harm', 'shelling civilians',
  ],
  tr: [
    'insan hakları', 'hak ihlali', 'hak savunucusu',
    'sivil', 'siviller',
    'mülteci', 'sığınmacı', 'yerinden edilen',
    'işkence', 'gözaltı', 'tutuklu', 'tutuklandı', 'cezaevi',
    'siyasi tutuklu', 'vicdan tutuklusu', 'kayıp', 'zorla kaybedilme',
    'idam', 'yargısız infaz',
    'savaş suç', 'insanlığa karşı suç', 'soykırım', 'etnik temizlik',
    'katliam', 'mezalim',
    'basın özgürlüğü', 'gazeteci öldürüldü', 'gazeteci tutuklandı', 'gazeteci gözaltı',
    'ifade özgürlüğü', 'toplanma özgürlüğü',
    'kadın hakları', 'kadın cinayeti', 'cinsel şiddet', 'cinsel saldırı',
    'çocuk hakları', 'çocuk işçi', 'çocuk gelin', 'çocuk asker',
    'azınlık hakları', 'yerli halk', 'lgbti',
    'insan kaçakçılığı', 'köle', 'zorla çalıştırma',
    'inanç özgürlüğü', 'devlet baskısı', 'siyasi baskı', 'zulüm', 'kıyım',
    'protesto', 'eylemci', 'gösterici',
    'açlık', 'kıtlık',
    'ayrımcılık',
  ],
  fr: [
    'droits humains', "droits de l'homme", 'violation des droits',
    'civil', 'civils', 'victimes civiles',
    'réfugié', 'réfugiés', 'asile', 'déplacé',
    'torture', 'détenu', 'détention', 'emprisonné', 'arrêté',
    'prisonnier politique', 'disparition forcée',
    'peine de mort', 'exécution',
    'crime de guerre', "crime contre l'humanité", 'génocide', 'nettoyage ethnique',
    'massacre', 'atrocité',
    'liberté de la presse', 'journaliste tué', 'journaliste détenu', 'journaliste emprisonné',
    "liberté d'expression", 'liberté de réunion',
    'droits des femmes', 'violence faite aux femmes', 'violence sexuelle', 'féminicide',
    "droits de l'enfant", 'travail des enfants', 'mariage forcé', 'enfant soldat',
    'droits des minorités', 'peuples autochtones', 'lgbt',
    'traite humaine', 'esclavage', 'travail forcé',
    'liberté religieuse', 'persécuté', 'persécution', 'répression',
    'manifestation', 'manifestant',
    'famine', 'famine', 'discrimination',
  ],
};

// ===== Negative keywords — auto-reject if any appear in title. =====
// Politics/economy/sport/entertainment + politician-quote markers that pollute general feeds.
module.exports.NEGATIVE = {
  en: [
    'stock market', 'stocks', 'shares', 'wall street', 'nasdaq', 'dow jones', 'ftse',
    'gdp', 'inflation', 'interest rate', 'central bank', 'earnings', 'quarterly',
    'crypto', 'bitcoin', 'ethereum', 'merger', 'acquisition', 'ipo',
    'box office', 'oscars', 'grammy', 'celebrity', 'netflix', 'streaming',
    'football match', 'premier league', 'olympics medal', 'world cup', 'champions league',
    'tennis', 'cricket', 'basketball', 'nba', 'nfl', 'formula 1',
    'tech stocks', 'apple inc', 'microsoft', 'google earnings',
    'royal family', 'royals', 'prince harry', 'king charles',
    'recipe', 'horoscope', 'weather forecast',
    'trump says', 'biden says', 'putin says', 'starmer says', 'sunak says',
    'election results', 'midterm', 'primary election', 'campaign rally',
    'parliament passes', 'congress votes', 'senate vote',
    'summit', 'g7 summit', 'g20', 'state visit', 'bilateral talks',
    'rate cut', 'rate hike',
  ],
  tr: [
    'borsa', 'hisse', 'döviz kuru', 'enflasyon', 'merkez bankası', 'faiz',
    'kripto', 'bitcoin',
    'şampiyonlar ligi', 'süper lig', 'galatasaray', 'fenerbahçe', 'beşiktaş', 'maç sonucu',
    'olimpiyat madalya', 'dünya kupası',
    'oscar', 'grammy', 'magazin',
    'tarif', 'burç',
    'trump:', 'putin:', 'erdoğan:', 'starmer:',
    'zirve', 'g20', 'g7', 'kabine',
    'milletvekili', 'parti yönetimi', 'genel kurul',
  ],
  fr: [
    'bourse', 'action', 'cac 40', 'inflation', 'banque centrale', "taux d'intérêt",
    'crypto', 'bitcoin', 'fusion-acquisition',
    'ligue 1', 'ligue des champions', 'coupe du monde', 'tournoi',
    'box-office', 'césar', 'cannes',
    'recette', 'horoscope', 'météo',
    'trump :', 'macron :', 'poutine :',
    'sommet', 'sommet du g7', 'sommet du g20',
    'élection présidentielle', 'campagne', 'second tour',
  ],
};
